### ISSUE TITLE
XY11 - Volcanion missing types

### ISSUE THREAD

**Issue by adback03** [PokemonTCG/pokemon-tcg-api#10]
http://api.pokemontcg.io/v1/cards/xy11-26

The 'types' field does not exist for this card.

**Comment by Eein** [comment]
Seems that maybe all dual types do not have this field.
http://api.pokemontcg.io/v1/cards/xy11-77 
also doesn't have it.

**Comment by adback03** [comment]
Yeah, I've noticed this for at least newer sets... Here is an example of a card that actually does have both types:

http://www.pokemon.com/us/pokemon-tcg/pokemon-cards/hgss-series/hgss2/90/
https://api.pokemontcg.io/v1/cards/hgss2-90

I think the best I'm going to be able to do right now is just fix them as they get reported...

**Comment by adback03** [comment]
I have cleaned up every card (with a supertype of Pokemon) that was missing the "types" field. This includes the following cards:

- xy11-11
- xy11-15
- xy11-26
- xy11-42
- xy11-64
- xy11-68
- xy11-77
- xy11-79
- xy11-107
- xy11-109
- xy11-112
- ecard2-179
- ex11-55
- ex11-58
- ex11-88
- ex2-14
- ex3-72
- ex4-50
- ex5-72
- ex7-56
- hgss4-101
- xy1-2
- xy1-30
