### ISSUE TITLE
Ability to search for multiple cards though multiple sets

### ISSUE THREAD

**Issue by RichardHpa** [PokemonTCG/pokemon-tcg-api#101]
Since every card has its own unique ID, it would be great if there was a way to be able to retrieve multiple cards in a single api search.
Since there is an api limit, if you wanted to retrieve all your cards in a 60 card deck. It would require 60 apis calls whichout using an api key, you wouldnt be able to do since you can only get 30 cards a minute.

So rather than saying
- https://api.pokemontcg.io/v2/cards/xy1-1
- https://api.pokemontcg.io/v2/cards/swsh1-1

maybe something like 
https://api.pokemontcg.io/v2/cards/xy1-1,swsh1-1

**Comment by jaymarvels** [comment]
You should already be able to do something like this already

i.e. cards/q=id:xy-1-1 OR id:swsh1-1

**Comment by RichardHpa** [comment]
oh of course. Didn't think of that. Il close this issue but for people who are interesting the api call would be `https://api.pokemontcg.io/v2/cards?pageSize=2&q=(id:xy1-1 OR id:swsh1-1)`
