### ISSUE TITLE
Establish differences in Abilities, Pokemon Powers and Poke-Powers/Poke-Bodies

### ISSUE THREAD

**Issue by aljabib** [PokemonTCG/pokemon-tcg-api#14]
Right now, the abilities attribute in cards are not classified as they are in the TCG; the very first were called Pokemon Powers, then in EXP-CoL there were Poke-Powers and Poke-Bodies, and finally in BW-on we just have Abilities.

You could try replacing abilities with pokemonPowers, pokePowers or pokeBodies (remember, Pokemon Powers and Poke-Powers are two different things) in cards that aren't in BW-on. In all cards from Base Set to Neo Destiny, replace abilities with pokemonPowers.

For example, https://api.pokemontcg.io/v1/cards/dp4-106 returns Palkia LV. X, who has a Poke-Power. However, this is erroneously set as an ability.

**Comment by adback03** [comment]
I'm going to address this in v1 of the API by adding a __type__ field the __ability__ property. So now you may see something like this:

`"ability":{"name":"Restructure","text":"Once during your turn.....","type":"Poke-POWER" }`

I think with V2 of the API, it may be worth breaking this apart and having two fields: ability and pokemonPower. The __pokemonPower__ field would then have a name, text, and type (either poke-power or poke-ability), and ability would stay the same. 

Does this solution for V1 sound okay to you?

**Comment by adback03** [comment]
This has now been released.
