### ISSUE TITLE
Baby Powers not present in sets

### ISSUE THREAD

**Issue by aljabib** [PokemonTCG/pokemon-tcg-api#15]
You should add the following to Baby Pokemon in the Neo and Ecard sets (they are the same):

"text":["If this Baby Pokémon is your Active Pokémon and your opponent tries to attack, your opponent flips a coin (before doing anything else required in order to use that attack). If tails, your opponent's turn ends without an attack."],

Also, the supertype for Cleffa in ecard3-48 is erroneously assigned as Energy when it should be Pokemon.

**Comment by adback03** [comment]
All baby pokemon in the Neo and Ecard sets have been fixed.
