### ISSUE TITLE
Add missing Secret Rares and Karen

### ISSUE THREAD

**Issue by Eein** [PokemonTCG/pokemon-tcg-api#16]
Karen will be standard legal october 7th
http://bulbapedia.bulbagarden.net/wiki/Karen_(XY_Promo_177)
was just printed for usa in the keldeo vs rayquaza deck and will follow the 3 fridays rule for offical play.

Some secret rares i know that are missing are 163/162 Mewtwo-EX, 164/162 Mewtwo-Ex and, 110/108 VS Seeker

Likely many more.

**Comment by adback03** [comment]
Yeah, I'm slowly working on figuring out which secret rares are missing. Which sets are those secret rares from that you pointed out?

**Comment by adback03** [comment]
All the cards pointed out in the original issue have now been added. I'll be opening a separate issue for additional secret rares.
