### ISSUE TITLE
Missing Scramble Energy from EX Deoxys set

### ISSUE THREAD

**Issue by braydeejohnson** [PokemonTCG/pokemon-tcg-api#18]
While pulling cards to cache, I noticed a missing card in the EX Deoxys Set. ex8-95 is missing and appears invalid. Here is the information I found on the card on bulbapedia.

http://bulbapedia.bulbagarden.net/wiki/Scramble_Energy_(EX_Deoxys_95)

I'll be working through the sets to cache each card, and am happy to report any others I find that are missing.

**Comment by braydeejohnson** [comment]
[Missing Cards.xlsx](https://github.com/PokemonTCG/pokemon-tcg-api/files/542221/Missing.Cards.xlsx)

**Comment by braydeejohnson** [comment]
As I mentioned, here is a list of cards I found were missing from the api. Not sure if you like it here or another issue. This one is specific to a single card.

**Comment by adback03** [comment]
Some of the promos I am still working on adding, but all the other missing cards in that list have been accounted for. I'm going to create a separate issue for the promos, as the original issue (missing scramble energy) has been resolved.
