### ISSUE TITLE
Add Trainer Packs to DB (especially Pikachu LIbre and Suicune)

### ISSUE THREAD

**Issue by ebetancourt** [PokemonTCG/pokemon-tcg-api#19]
I can see this is an issue with the actual database at pokemon.com. I am not sure if this is something you account for, but some sets are not listed on pokemon.com's card database. For example http://bulbapedia.bulbagarden.net/wiki/XY_Trainer_Kit:_Pikachu_Libre_%26_Suicune_(TCG) Its something they just started selling in April, and while most of the cards are copies of cards found elsewhere in XY, they do have their own numbers and set markers. The titular Pikachu Libre and Suicune cards are also different from all of the cards listed on their database.

**Comment by adback03** [comment]
Deck info is now being tracked here: https://github.com/PokemonTCG/pokemon-tcg-data/tree/master/json/decks

If you notice any decks missing, please create an issue in the other repo. Thanks!
