### ISSUE TITLE
Add the missing XY Promos

### ISSUE THREAD

**Issue by adback03** [PokemonTCG/pokemon-tcg-api#21]
Refer to #18 for a list of reported cards. Some of those have been accounted for already.

**Comment by adback03** [comment]
Here is a list of promos to obtain:

XY119
XY120
XY157
XY158
XY159
XY160
XY161
XY173
XY174
XY175
XY176
XY183

BW77
BW78

**Comment by adback03** [comment]
Updated list:

XY160
XY161
XY183

BW77
BW78

**Comment by butterEbrett** [comment]
I created a [pull request](https://github.com/PokemonTCG/pokemon-tcg-data/pull/3) that adds the data for the cards in the "updated list"

**Comment by adback03** [comment]
@butterEbrett thanks, hopefully I can get to it tonight.
