### ISSUE TITLE
Trademark / copyright issues?

### ISSUE THREAD

**Issue by thejmsill** [PokemonTCG/pokemon-tcg-api#22]
First off, super cool api thanks for making it!  

Just wondering about trademarks / copyright when making an app/website using the data. Is this going to get a Cease and Desist notice from Nintendo?   

Any thoughts on that?

**Comment by adback03** [comment]
I would certainly hope it wouldn't get shut down, but it is difficult to predict. I tried to provide at least some sort of notice that my site is not supported/affiliated with them through the following remark:

> This website is not produced, endorsed, supported, or affiliated with Nintendo or The Pokémon Company

Unfortunately, there isn't much more I can do than that. There are so many third party pokemon related sites out there though, that I'm not overlay concerned.

**Comment by thejmsill** [comment]
Thanks for getting back to me. 

And ya, I agree. Was just curious on others perspectives and seemed like a good place to start the discussion. 

I have a simple app idea I'll post when ready.
