### ISSUE TITLE
Add expandedLegal set parameter

### ISSUE THREAD

**Issue by Sylencia** [PokemonTCG/pokemon-tcg-api#23]
I'm potentially looking to use this api and have been thinking about adding Standard/Expanded legal toggles but I found there's no option to query for expanded legal sets.

**Comment by adback03** [comment]
This should be easy to do. I'll try to get this added this week.

**Comment by adback03** [comment]
This has been added in v1.7.2.

`https://api.pokemontcg.io/v1/sets` now also includes `expandedLegal`.
