### ISSUE TITLE
Last page of cards from DRX is missing

### ISSUE THREAD

**Issue by mmxxiii** [PokemonTCG/pokemon-tcg-api#24]
http://www.pokemon.com/us/pokemon-tcg/pokemon-cards/11?6-black-white=

bw6 (Dragons Exalted aka DRX) cards 121 and up are not present:

http://api.pokemontcg.io/v1/cards/bw6-121
http://api.pokemontcg.io/v1/cards/bw6-122
http://api.pokemontcg.io/v1/cards/bw6-123
...

**Comment by adback03** [comment]
This has been fixed in v1.7.2.
