### ISSUE TITLE
bwp-BW47 name formatted incorrectly

### ISSUE THREAD

**Issue by mmxxiii** [PokemonTCG/pokemon-tcg-api#26]
The card name for bwp-BW47 is formatted as "Rayquaza ex", but should be formatted as "Rayquaza-EX" (as it is for bw6-85, xy6-60, xy6-75, xy6-104, xyp-XY66, xyp-XY69, and xyp-XY73).

**Comment by marcoescher** [comment]
The same goes with all the other BWP Pokémon-ex, here's the full list:

Reshiram-EX BWP BW36
Kyurem-EX BWP BW37
Zekrom-EX BWP BW38
Mewtwo-EX BWP BW45
Darkrai-EX BWP BW46
Rayquaza-EX BWP BW47
Keldeo-EX BWP BW61
Black Kyurem-EX BWP BW62
White Kyurem-EX BWP BW63
Thundurus-EX BWP BW81
Deoxys-EX BWP BW82
Lugia-EX BWP BW83
Tornadus-EX BWP BW96

**Comment by adback03** [comment]
Yeah, this seems to be a mistake on pokemon.com as well. I'll have to go through and manually clean these up.

**Comment by adback03** [comment]
These have all been cleaned up with version 1.7.4.
