### ISSUE TITLE
Editable file of missing cards

### ISSUE THREAD

**Issue by marcoescher** [PokemonTCG/pokemon-tcg-api#27]
I've collected all the missing cards I found in an editable Google Spreadsheets file. Feel free to contribute.

Cards available on Pokemon.com should already be “fetchable” by @adback03, while the others need the manual or scraping treatment.

http://bit.ly/PTCGApiMissing

**Comment by adback03** [comment]
Thanks for putting this together. I'll go through this and try to knock out all the ones available on pokemon.com first.

**Comment by butterEbrett** [comment]
Added the Unown from EX Unseen Forces and created a pull request

**Comment by adback03** [comment]
Closing. All data issues are being tracked in the data repo.
