### ISSUE TITLE
expandedLegal=true includes sets where expandedLegal=false

### ISSUE THREAD

**Issue by mmxxiii** [PokemonTCG/pokemon-tcg-api#28]
https://api.pokemontcg.io/v1/sets?expandedLegal=true

The opposite is also true.

https://api.pokemontcg.io/v1/sets?expandedLegal=false

Basically, it returns all sets regardless. Seems parameter is being ignored.

**Comment by adback03** [comment]
I'll update this tonight. Forgot to make the new field queryable, so yes, it is just getting ignore right now.
