### ISSUE TITLE
BW Black Star Promos listed as standardLegal and XY Black Star Promos not?

### ISSUE THREAD

**Issue by mmxxiii** [PokemonTCG/pokemon-tcg-api#29]
```
{"code":"bwp","name":"BW Black Star Promos","series":"BW","totalCards":101,"standardLegal":true,"expandedLegal":true,"releaseDate":"03/01/2011"}
```
```
{"code":"xyp","name":"XY Black Star Promos","series":"XY","totalCards":183,"standardLegal":false,"expandedLegal":true,"releaseDate":"10/12/2013"}
```

While some BW promos are standard legal due to reprints, most are not.

Also, not sure if it is better to list XY promos as standard legal or not, since most are, but some have rotated.

**Comment by adback03** [comment]
Yeah, I believe it is XY36+ are legal. I'll update BW promos to be false, and XY to true.

I'm still working on a future enhancement that will have legality at a card level, so that promos and banned cards are better represented.

**Comment by adback03** [comment]
This has been updated.
