### ISSUE TITLE
Enhancement request: Negative query parameters

### ISSUE THREAD

**Issue by mmxxiii** [PokemonTCG/pokemon-tcg-api#30]
For example, if I want to find all EXs in XY series, but don't want to find ones from Double Crisis.
Something like ``...?series=XY&subtype=EX&setCode=!dc1`` which would result in an sql query like ``...WHERE `series` LIKE '%XY%' AND `subtype` LIKE '%EX%' AND `setCode` NOT LIKE '%dc1%'``
Obviously the results could be filtered on my end after the query is processed instead, but it would be convenient to be able to get all non-EX Pokemon, or all psychic types except Gengar, etc. in the result set rather than having to filter on my end.

**Comment by adback03** [comment]
Negative query parameters are now supported in V2.

`/v2/cards?q=set.series:XY subtypes:EX -set.id:dc1`
