### ISSUE TITLE
Using | (logical OR) in nationalPokedexNumber query returning either no results or odd results

### ISSUE THREAD

**Issue by mmxxiii** [PokemonTCG/pokemon-tcg-api#31]
So, I was doing a query looking for starters from all generations printed in XY series:
http://api.pokemontcg.io/v1/cards?supertype=Pokemon&nationalPokedexNumber=1|4|7|152|155|158|252|255|258|387|390|393|495|498|501|650|653|656&series=XY
This returned no results.

I then decided that maybe my query was too long, and removed the last 3:
http://api.pokemontcg.io/v1/cards?supertype=Pokemon&nationalPokedexNumber=1|4|7|152|155|158|252|255|258|387|390|393|495|498|501&series=XY
This returns a few Pansage (nationalPokedexNumber=511) .

Next, I tried looking for only the Gen6 starters:
http://api.pokemontcg.io/v1/cards?supertype=Pokemon&nationalPokedexNumber=650|653|656
This returns a bunch of Florges (nationalPokedexNumber=671).

??? Not sure what is going on.

**Comment by mmxxiii** [comment]
And now that I look at the documentation, i see that nationalPokedexNumber doesn't support lists, so I guess this is a feature request?

**Comment by adback03** [comment]
The `nationalPokedexNumber` query parameter now supports a list of values.  Your queries above should work as expected.
