### ISSUE TITLE
attackCost queries return error

### ISSUE THREAD

**Issue by mmxxiii** [PokemonTCG/pokemon-tcg-api#32]
e.g. - http://api.pokemontcg.io/v1/cards?attackCost=Fire returns `{"status":"500","error":"Internal Server Error"}`.

**Comment by adback03** [comment]
So I realize now that `attackCost` is named poorly, and should be `attackConvertedEnergyCost`. That field takes an integer, or can use the `gt, lt, gte, lte` syntax. What I can try to do in the meantime is create an attackCostType field. Otherwise, this seems like a version 2 change.

**Comment by mmxxiii** [comment]
attackCostType would work for my purposes. I assume it would search for matching values within the array found at `cards[x]->attack[x]->cost['val','val','val']`?

**Comment by adback03** [comment]
Attack cost will be filterable in the v2 api. A beta will be out in the next couple weeks,

**Comment by adback03** [comment]
V2 is now publicly available, and you can use the range filters on attack cost (or just a single number):

`/v2/cards?q=attacks.convertedEnergyCost:[3 TO 5]`

Additionally, for the cost itself (Fire, Fire), you can search like this:

`/v2/cards?q=attacks.cost:fire`
