### ISSUE TITLE
Enhancement request: Searching all energy types in pokemon type and attack costs

### ISSUE THREAD

**Issue by mmxxiii** [PokemonTCG/pokemon-tcg-api#33]
This one is probably a bit specific to me, so I understand if it is not worth the effort for you.

Basically, I have a fun format I've developed that limits the cards you can include in your deck by the type and attack cost types of a single pokemon card (this is called the pokemon's Type-Identity). (if you want to know more: http://www.northvalleypokemon.org/partner/ ). Because of this limitation, many players would like to be able to find a list of cards that includes all of the types they want to play. The query for this would look something like `SELECT * FROM cards WHERE CONCAT(type, attackCost) LIKE "%Water%" AND CONCAT(type, attackCost) LIKE "Fire" AND CONCAT(type, attackCost) LIKE "Lightning"` for pokemon with a Water+Fire+Lightning Type-Identity. I am unsure how the attack costs are stored in the database for pokemon that have multiple attacks, but I assume the query would be more complicated that the short line I have written here.

If I were to attempt to fetch all possible matches and then filter on my end, it would take several calls to the api for each search (1+ calls per type searched, because of pagination), and then I'd have to sift through EVERY card ever made that included that 1 type looking for matches in the attack cost for the other types in the search. Ultimately, it would be easier for me to replicate your database only keeping the fields that concern me.

**Comment by adback03** [comment]
V2 has a more advanced query syntax that allows for logical ands, ors, and other operators. I believe this issue is resolved by using V2. Here are some sample results when filtering on attack cost of fire, water and lightning.

https://pokemontcg.guru/search?q=attacks.cost%3Afire+attacks.cost%3Awater+attacks.cost%3Alightning
