### ISSUE TITLE
Multiple abilities on a card

### ISSUE THREAD

**Issue by Sylencia** [PokemonTCG/pokemon-tcg-api#34]
Not sure how many cards this affects, but there are some cards where there is both a Pokebody and PokePower such as:
https://api.pokemontcg.io/v1/cards?name=Snorlax&setCode=ex15
https://pkmncards.com/card/snorlax-dragon-frontiers-df-10/

As such, only the first ability is shown, and the second is missing.

**Comment by adback03** [comment]
Darn, didn't realize this was possible. Unfortunately this would be a breaking change, so I'm going to set this for a version 2 milestone. I'm expecting to start development on version 2 relatively soon, but this might take a bit to fix.

**Comment by adback03** [comment]
Closing as it is being tracked in the data repo: https://github.com/PokemonTCG/pokemon-tcg-data/issues/94
