### ISSUE TITLE
text parameter not working (i.e. it returns everything).

### ISSUE THREAD

**Issue by mmxxiii** [PokemonTCG/pokemon-tcg-api#36]
I discovered this while trying to find `supertype=trainer` cards that contained the word `supporter` in the card text. When Paint Roller came up as the first result, I was confused. Further testing revealed that no matter what I put after `text=` it returned every card that matched the other parameters.

I tried to think of a word that would appear on relatively few cards for the example:

https://api.pokemontcg.io/v1/cards?text=imakuni

**Comment by adback03** [comment]
This issue no longer appears to be an issue.

Example:

https://api.pokemontcg.io/v1/cards?supertype=trainer&text=supporter
