### ISSUE TITLE
Electrode (EVO 40) errata

### ISSUE THREAD

**Issue by marcoescher** [PokemonTCG/pokemon-tcg-api#37]
Electrode from Evolutions has been errata'd ([source](http://www.pokemon.com/us/pokemon-news/errata-for-electrode-in-pokemon-tcg-xy-evolutions/)).

The correct text for Electrode’s “Buzzap Thunder” Ability is now the following:

> Once during your turn (before your attack), you may Knock Out this Pokémon and attach it to one of your Lightning-type Pokémon as a Special Energy card. This card provides 2 Lightning Energy only while this card is attached to a Pokémon.

This was the previous text, now overruled (emphasis mine):

> Once during your turn (before your attack), you may Knock Out this Pokémon and attach it to one of your Lightning-type Pokémon as a Special Energy card. This card provides 2 Lightning Energy only while this card is attached to a **Lightning Pokémon**.

The Pokemon.com database had both its text and image updated.

**Comment by adback03** [comment]
It looks like the API already has the correct text. I don't see an updated image on Pokemon.com though. Can you link me to where you are looking?

**Comment by marcoescher** [comment]
There's a misunderstanding: the first text I posted is the correct version. This is the relative pic: http://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_40.png
