### ISSUE TITLE
Energy Cards Missing Type Field

### ISSUE THREAD

**Issue by doeiqts** [PokemonTCG/pokemon-tcg-api#38]
Energy cards don't have a field on them that seem to use the Type enumeration. Seems like something similar to how Pokemon cards have the Types field should be possible.

**Comment by adback03** [comment]
Energy cards have a supertype and subtype. They don't have a 'Types' field, because that field refers to energy types, which energy cards do not have (the energy types in the upper right hand corner).

**Comment by doeiqts** [comment]
I know, I'm requesting that you add a "Types" field.

What type of energy is a Grass Energy and how many energies does it provide? What about the Double Colorless Energy? Rainbow Energy?

There's no way to programmatically get that information from the API right now.

**Comment by adback03** [comment]
That's the thing, a Grass Energy doesn't have a type of energy. It IS the energy card itself. The type section isn't even on the actual cards. What does adding the types section give you that you don't already have?

**Comment by doeiqts** [comment]
That's what I mean. A Grass Energy, by definition, IS Grass. But there's no programatic way to know that in the API at the moment. I can only tell that it's an Basic (subtype) Energy (supertype), but now what type of energy it provides.

Say a Pokemon's attack requires 2 Fire type energy. This is programmatically known via the Attack's Cost field, which is a List of Types. Right now, there's no way to match up the Fire Energy card to that Fire type that's listed in attack.cost.

Same thing with a Double Colorless Energy. What Type of energy does it provide? The Type Enum should be able to be used for both Pokemon cards and Energy cards, but right now there's no where that the Type Enum is being used on the Energy cards.

Also in the Double Colorless Energy example, there's no way to know how many energy is provided by the card. Both Type of energy provided and amount of energy provided does not come back in the API currently, and it would be a lot better if it did.

Right now, I can create a Pokemon object, and I can create an Energy object, and I can link them together. But I still have no way of knowing whether the Pokemon can use a particular Attack object without knowing what kind (Type and amount) of Energy object is attached to that Pokemon.
