### ISSUE TITLE
Secret Rares have odd rarities

### ISSUE THREAD

**Issue by doeiqts** [PokemonTCG/pokemon-tcg-api#39]
Secret rare cards (any card with a set number greater than the number of cards in a set) seem to have inconsistent Rarity field values.

https://api.pokemontcg.io/v1/cards/xy12-109 has Rare Holo, even though the card isn't holo.
https://api.pokemontcg.io/v1/cards/xy9-123 has Rare Holo too, though it's an EX card.

Other secret rares are just missing, but that's another issue.

Can we get a "Rare Secret" value added to the existing Rarity enumeration for any card over the maximum set number?

**Comment by adback03** [comment]
Interesting, even Pokemon.com has both of those cards listed as Rare Holos. I could look into changing the rarity of 'Secret Rares' to 'Secret Rare'.

**Comment by doeiqts** [comment]
Thanks. As long as they're grouped together under a single rarity I'd be fine with that, but I might suggest "Rare Secret" in keeping with your existing list of rarities:

Common
Uncommon
Rare
Rare Holo
Rare BREAK
Rare Holo EX
Rare Ultra

But up to you.

**Comment by adback03** [comment]
Rare Secret has been in the data for awhile. It is possible some cards aren't flagged correctly, so any data specific issues can get reported to the data repo. "Rare Secret" would be the rarity to use for those cards.
