### ISSUE TITLE
Unresolved images in the Fates Collide series

### ISSUE THREAD

**Issue by StrategistXIV** [PokemonTCG/pokemon-tcg-api#4]
I figured out that the following links are not working anymore:

https://s3.amazonaws.com/pokemontcg/xy10/82.png
https://s3.amazonaws.com/pokemontcg/xy10/121.png

Not sure what is wrong though:P

**Comment by adback03** [comment]
That's odd, they appear to be broken image links from the official pokemon site too (where I typically get images from).

http://www.pokemon.com/us/pokemon-tcg/pokemon-cards/xy-series/xy10/82/
http://www.pokemon.com/us/pokemon-tcg/pokemon-cards/xy-series/xy10/121/

I'll have to look for these images elsewhere.

Thanks for pointing this out!

**Comment by adback03** [comment]
Even Bulbapedia doesn't have the English images for the cards...I'll keep looking, but if you find someplace with decent images let me know!

**Comment by StrategistXIV** [comment]
I'll let you know if I find any! Do you mean decent images in general by the way? Or specifically the images ment below? The current images are a little blurry to read when you zoom in, so maybe it would be nice if we could replace them by higher quality images eventually? (Or add a new attribute with for a URL for higher quality images so that the current images can still use the smaller sized current ones.)

And no probs by the way! If I get the chance I will also email the pokemon.com about their missing images:P I'll let you know if I get anything in return!

**Comment by StrategistXIV** [comment]
They told me they passed it on to the development team, but they couldn't give an indication of how long that would take. So let's hope they will fix it soon.

**Comment by StrategistXIV** [comment]
@adback03 They updated the images! The API is not updated yet though!

**Comment by adback03** [comment]
These images have now been updated. Thanks for the heads up!
