### ISSUE TITLE
Set object and Pokemon set information differ

### ISSUE THREAD

**Issue by doeiqts** [PokemonTCG/pokemon-tcg-api#41]
Using https://api.pokemontcg.io/v1/sets there is clearly a schema for a Set object.

However, when looking at a card like https://api.pokemontcg.io/v1/cards/xy8-143 the Set object schema isn't used. Instead, there are individual fields that are similar to the Set schema:

card.set = set.name
card.setCode = set.code
card.series = set.series
etc

Could we not use card.set.name, card.set.code, and card.set.series? Basically using the same Set object as just a field on the Card object?

**Comment by adback03** [comment]
I am most likely going to be going the route of using JSON API Spec (http://jsonapi.org/). If I do this, this should help clear up any schema confusion, and would also address this issue. Unfortunately, as this is clearly a breaking change, this will have to be addressed with version 2 of the API.

**Comment by adback03** [comment]
Set information is now embedded within the card itself in V2, so closing this issue.
