### ISSUE TITLE
What's the set code for XY Promos? Isn't it xyp?

### ISSUE THREAD

**Issue by comp0cker** [PokemonTCG/pokemon-tcg-api#42]
For example, the link https://api.pokemontcg.io/v1/cards/xyp-1 doesn't work. Thanks!

**Comment by mmxxiii** [comment]
You have to use the correct card number which, for XY promos, begin with XY. E.g. - https://api.pokemontcg.io/v1/cards/xyp-xy01

**Comment by comp0cker** [comment]
thanks!
