### ISSUE TITLE
Deoxys formes

### ISSUE THREAD

**Issue by marcoescher** [PokemonTCG/pokemon-tcg-api#54]
Deoxys formes from EX era shouldn't have the forme in their name (you can't have more than 4 of it in a deck).

(Please note that this doesn't regard DP-era Deoxys.)

So it should be, for example:
Deoxys [Normal Forme] (ex8-16) -> Deoxys (ex8-16)

**Affected cards:**
ex8-16
ex8-17
ex8-18
ex9-2
pop4-2 (also incorrectly spelled “(Delta species)” instead of "δ")
pop4-17

**Comment by marcoescher** [comment]
(Updated with clarification on DP-era Deoxys)

**Comment by adback03** [comment]
For pop4-2, should the name just be "Deoxys"?

**Comment by marcoescher** [comment]
In the API Delta species Pokémon are currently formatted as "NAME δ", so to keep it consistent the name should be "Deoxys δ".

However, on a game perspective, a "Deoxys" (say, ex8-18) and a "Deoxys δ" (pop4-2) have the same name, so you can't have 3 of the first one and 2 of the second one in a deck.
So you might consider to remove the "δ" from each name and add "δ Species" as an additional property instead.

**Comment by adback03** [comment]
Okay, we can make a separate issue for that. The Deoxys forms have been removed from their names.
