### ISSUE TITLE
Pokémon Star don't have the "Star" in their name

### ISSUE THREAD

**Issue by marcoescher** [PokemonTCG/pokemon-tcg-api#55]
[Pokémon Star](http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_%E2%98%86_(TCG)) don't have any “Star” (official transcript of this symbol: ![image](https://cloud.githubusercontent.com/assets/4488072/25529224/7dd2e552-2c21-11e7-899a-f1b383edd25e.png)) in their name.

So it should be, for example:

Latias (ex8-105) -> Latias Star (ex8-105)

**Comment by adback03** [comment]
These have been updated.
