### ISSUE TITLE
imageUrl of some cards returning card back

### ISSUE THREAD

**Issue by marcoescher** [PokemonTCG/pokemon-tcg-api#56]
The imageUrl parameter for Kabutops ex (ex2-97) and Scramble Energy (ex8-95) return a card back instead of the actual scan. There may be other cards with the same bug, I'll update the list if I'll find more.

**Comment by adback03** [comment]
Thanks, I'll take a look. The card back gets returned if the image wasn't found, so I'll check it out.

**Comment by marcoescher** [comment]
Found more (all from Aquapolis):

Cubone	(ecard2-72)
Doduo	(ecard2-73)
Drowzee	(ecard2-74)
Eevee	(ecard2-75)
Exeggcute	(ecard2-76)
Goldeen	(ecard2-78)
Grimer	(ecard2-79)
Hitmonchan	(ecard2-81)
Hitmontop	(ecard2-82)
Horsea	(ecard2-84)
Horsea	(ecard2-85)
Houndour	(ecard2-87)
Kangaskhan	(ecard2-88)
Magnemite	(ecard2-91)
Porygon	(ecard2-103)
Psyduck	(ecard2-104)
Tentacool	(ecard2-113)
Vulpix	(ecard2-116)
Juggler	(ecard2-126)
Memory Berry	(ecard2-128)
Metal Cube 01	(ecard2-129)
Pokémon Park	(ecard2-131)
Traveling Salesman	(ecard2-137)
Weakness Guard	(ecard2-141)

**Comment by adback03** [comment]
These images have all been added. You might not see them right away due to caching, but check back again in a bit.
