### ISSUE TITLE
Pokémon SP don't have the owner's suffix in their name

### ISSUE THREAD

**Issue by marcoescher** [PokemonTCG/pokemon-tcg-api#57]
(Similar to #55) 

[Pokémon SP](http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_SP_(TCG)) don't have the owner's suffix in their name.

The official suffixes for SP Pokémon are:

![image](https://cloud.githubusercontent.com/assets/4488072/25557198/0e1dc26c-2d0d-11e7-9c61-aa0b65787813.png) -> G
![image](https://cloud.githubusercontent.com/assets/4488072/25557199/14593544-2d0d-11e7-8825-8b9262bb7070.png) -> GL
![image](https://cloud.githubusercontent.com/assets/4488072/25557205/4bc8857a-2d0d-11e7-8b77-b5f71b51112d.png) -> 4
![image](https://cloud.githubusercontent.com/assets/4488072/25557206/5527e1c4-2d0d-11e7-93e4-56b9866a8837.png) -> C
![image](https://cloud.githubusercontent.com/assets/4488072/25557210/5cf0c740-2d0d-11e7-9850-e1d0a0b8c39f.png) -> FB
![image](https://cloud.githubusercontent.com/assets/4488072/25557211/62984916-2d0d-11e7-855a-ed5cba2ed12c.png) -> M

So it should be, for example:

Dialga (pl1-7) -> Dialga G (pl1-7)

**Comment by adback03** [comment]
This has been addressed.
