### ISSUE TITLE
Pokémon accent missing on older cards, can't be retrieved by the API

### ISSUE THREAD

**Issue by marcoescher** [PokemonTCG/pokemon-tcg-api#59]
The “é” accent is missing on some older cards that currently feature the word “Pokemon” or “Poke”.

For some reason, this makes them unretrievable by typing the full name ([example](http://api.pokemontcg.io/v1/cards?name=Pokemon%20Breeder)).

Here's a list of the affected cards:

(base1-76) "Pokemon Breeder"
(base1-77) "Pokemon Trader"
(base1-85) "Pokemon Center"
(base4-105) "Pokemon Breeder"
(base4-106) "Pokemon Trader"
(base4-114) "Pokemon Center"
(base6-102) "Pokemon Breeder"
(base6-103) "Pokemon Trader"
(basep-40) "Pokemon Center"
(basep-42) "Pokemon Tower"
(neo1-88) "PokeGear"
(neo1-95) "New Pokedex"
(neo1-102) "Pokemon March"
(neo3-62) "Pokemon Breeder Fields"
(neo4-102) "Pokemon Personality Test"
(ecard1-145) "Pokemon Nurse"
(ecard1-146) "Pokemon Reversal"
(ecard2-130) "Pokemon Fan Club"
(ecard2-131) "Pokemon Park"
(pop2-10) "Pokemon Park"
(pop4-9) "Pokemon Fan Club"

**Comment by adback03** [comment]
These have all been fixed.
