### ISSUE TITLE
Better quality cards and additional promo sets

### ISSUE THREAD

**Issue by StrategistXIV** [PokemonTCG/pokemon-tcg-api#6]
I found this website (http://colnect.com/en/trading_card_games/sets/game/22280-Pok%C3%A9mon_TCG) with good card images and additional promo sets, maybe we could include these in the API?

**Comment by StrategistXIV** [comment]
Comparison:

https://s3.amazonaws.com/pokemontcg/gym1/1.jpg
http://i.colnect.net/images/b/1132/225/Blaine--s-Moltres.jpg
http://i.colnect.net/images/b/1132/089/Blaine--s-Moltres.jpg

**Comment by adback03** [comment]
That's awesome, thanks! It will take quite some time to do these updates, but I'll let you know my progress.

**Comment by StrategistXIV** [comment]
Hey! Any progress on this?:P If I can do anything, please let me know.

**Comment by adback03** [comment]
Sorry, unfortunately I haven't really made progress on this yet. But yes, help would be great! If you want to send me your email address, I'll give you access to a dropbox folder where you can drop the higher res images. You can email me at backes.andrew@gmail.com if you'd rather not post your email here.

**Comment by adback03** [comment]
Update: I have been actively working on this, and just about have hi-res images for every set. I'm still trying to figure out logistics for hosting and then I'll plan a release. I'm hoping to release the new images sometime in October.

**Comment by StrategistXIV** [comment]
Good work! Things are also quite busy at my side here so sorry for the delay:P

**Comment by inergy** [comment]
any update on this?

**Comment by adback03** [comment]
@inergy so I have a lot of the hi-res cards, but I've held off on releasing due to the possibility of my S3 buckets being DDosed. Amazon S3 doesn't have usage restrictions it seems like, so if somebody just setup a service to constantly download my images, I would get a huge S3 bill in the mail. Right now my plan is to lock the images behind an API that has rate limiting to prevent this from happening.

**Comment by adback03** [comment]
I have a solution that seems to be working. This should hopefully be released this week. Sample URL: https://images.pokemontcg.io/sm1/12_hires.png

Will close this out once the urls in the API get updated.

**Comment by adback03** [comment]
Hires images are now available via the `imageUrlHiRes` field.
