### ISSUE TITLE
Tapu Bulu GX card - missing

### ISSUE THREAD

**Issue by newtmitch** [PokemonTCG/pokemon-tcg-api#62]
Apparently there's an SM Promo card that's missing: http://shop.tcgplayer.com/pokemon/sm-promos/tapu-bulu-gx-sm32

I can't seem to find it on the official Pokemon TCG card lookup, either, so that's a bit weird...

**Comment by adback03** [comment]
Looks like I'll need to add quite a few missing Sun + Moon promos.

**Comment by newtmitch** [comment]
Sorry about that. :( Let's blame my son!

**Comment by adback03** [comment]
I don't remember when I added this, but I apparently did. Sorry for not closing!
