### ISSUE TITLE
Elekid (neo1-22) missing Pokémon Power

### ISSUE THREAD

**Issue by jugolm** [PokemonTCG/pokemon-tcg-api#63]
**Playful Punch**: Once during your turn (before your attack), you may flip a coin. If heads, do 20 damage to your opponent's Active Pokémon. (Apply Weakness and Resistance.) Either way, this ends your turn. This power can't be used if Elekid is Asleep, Confused, or Paralyzed.

Worth noting the card doesn't have any attack, only the Pokémon Power.

**Comment by adback03** [comment]
Thanks, this has been resolved.
