### ISSUE TITLE
Hi-res BREAK cards are landscape instead of portrait

### ISSUE THREAD

**Issue by marcoescher** [PokemonTCG/pokemon-tcg-api#65]
Example:

Golduck BREAK: https://images.pokemontcg.io/xy9/18.png
Golduck BREAK (hi-res): https://images.pokemontcg.io/xy9/18_hires.png

The reason is that hi-res scans are probably taken from Pkmncards, where the BREAK cards come with two different urls:

https://pkmncards.com/wp-content/uploads/golduck-break-breakpoint-bkp-18.jpg (Portrait)
https://pkmncards.com/wp-content/uploads/golduck-break-breakpoint-bkp-18-rotated.jpg (Landscape)

I guess it's just a matter of adding an IF to the import script.

**Comment by adback03** [comment]
These images have been fixed. It might take some time for the updates to appear due to caching.
