### ISSUE TITLE
[Feature] Add in numeric Retreat Energy cost

### ISSUE THREAD

**Issue by jaymarvels** [PokemonTCG/pokemon-tcg-api#66]
Similar to attack costs ("convertedEnergyCost") it would be useful to have something similar for retreat costs, for example "convertedRetreatEnergyCost"

**Comment by mmxxiii** [comment]
https://github.com/PokemonTCG/pokemon-tcg-api/commit/42df7b34794467b29d8a7bedf441f11646704ab9
