### ISSUE TITLE
Missing Card

### ISSUE THREAD

**Issue by jaymarvels** [PokemonTCG/pokemon-tcg-api#67]
Tapu Koko Promo is missing but appears on the pokemon.com database:

https://www.pokemon.com/us/pokemon-tcg/pokemon-cards/?cardName=koko&cardText=&evolvesFrom=&simpleSubmit=&format=unlimited&hitPointsMin=0&hitPointsMax=250&retreatCostMin=0&retreatCostMax=5&totalAttackCostMin=0&totalAttackCostMax=5&particularArtist=

**Comment by adback03** [comment]
This has been added. Thanks!
