### ISSUE TITLE
Pokemon cards price

### ISSUE THREAD

**Issue by SoutoRafaelB** [PokemonTCG/pokemon-tcg-api#68]
Hi,

I want to know if this or any other api has the actual prices of the cards in the market

**Comment by jaymarvels** [comment]
@SoutoRafaelB 

I think that would be highly unlikely to be included into this SDK. Prices fluctuate and most of the card resellers (troll and toad etc) have their own API's which you can hook into for card prices.

**Comment by adback03** [comment]
If you want prices, I'd recommend checking out TCGPlayer's API. This API currently has no plans to contain pricing data.
