### ISSUE TITLE
Cannot query for zero retreatCost

### ISSUE THREAD

**Issue by butterEbrett** [PokemonTCG/pokemon-tcg-api#73]
Cards with no retreat cost do not have a retreatCost attribute. The logic for querying against it doesn't seem to take NULL values into account. No results are returned in either of these scenarios:

 ~/cards?retreatCost=0
 ~/cards?retreatCost=lt1 (less than 1)

**Comment by adback03** [comment]
You can now do `/cards?convertedRetreatCost=0`

The `gt`, `lt`, `gte` and `lte` filters are also supported for this field.
