### ISSUE TITLE
Aquapolis Numbering (no "H" subset numbering)

### ISSUE THREAD

**Issue by daMoose52** [PokemonTCG/pokemon-tcg-api#74]
The Aquapolis holos H series are not numbered or designated so in the DB; they are simply 151, 152, etc. instead of H1, H2, etc.

**Comment by daMoose52** [comment]
There are also 4 "dot code" variants, numbered XXa, XXb which are not so-numbered in the database:  Golduck (50a, 50b), Drowzee (74a, 74b), Mr. Mime (95a, 95b), and Porygon (103a, 103b)
Details on both elements: 
https://www.flipsidegaming.com/blogs/pokemon-blog/retrospective-aquapolis

**Comment by adback03** [comment]
The numbers are correct, but the IDs of these cards will change in v2. Issue is getting tracked here: https://github.com/PokemonTCG/pokemon-tcg-data/issues/126
