### ISSUE TITLE
Missing features in the javascript implementation

### ISSUE THREAD

**Issue by keeshii** [PokemonTCG/pokemon-tcg-api#75]
Hi, I was writing a simple application in Angular, unfortunately the official javascript SDK is missing some features and there is no typings for typescript. I have decided to make my own implementation for your sdk, here is what I have got: https://github.com/keeshii/ptcg-api. Maybe it will help you improve the your official library.

Regards, and thanks for the great API :)

**Comment by adback03** [comment]
Hello! There is also a typescript sdk available: https://github.com/PokemonTCG/pokemon-tcg-sdk-typescript

Thank you :)

**Comment by keeshii** [comment]
Oh, I didn't noticed this repo. I suggest to add this link to the documentation.
