### ISSUE TITLE
"RR" is used as ptcgosetcode for 2 different sets

### ISSUE THREAD

**Issue by mmxxiii** [PokemonTCG/pokemon-tcg-api#76]
Team Rocket Returns, and Rising Rivals both use the ptcgocode "RR".

https://api.pokemontcg.io/v1/sets?ptcgoCode=RR

This is a known issue with the source I assume you got the codes from.

The unofficial, yet commonly used abbreviation for Team Rocket Returns has been TRR since Rising Rivals was released.

**Comment by adback03** [comment]
This was fixed awhile ago.
