### ISSUE TITLE
Searching for "N" is a pain

### ISSUE THREAD

**Issue by cssagogo** [PokemonTCG/pokemon-tcg-api#81]
Searching for the supporter card "N" is a pain.  If you try it today, it shows up way, way down the list.  Could you return exact matches first and then do contains second, or offer some other way to get it to the top of the list?  Support for star selectors?

```
"N" exact match
"N*" starts with
"*N" ends with
"*N*" contains
```

Just throwing it out there.  Not sure what API standards would be for something like this.

**Comment by adback03** [comment]
Star selectors could be a good idea to introduce. Have you tried putting quotes around your search? For example: `https://api.pokemontcg.io/v1/cards?name="n"`

**Comment by cssagogo** [comment]
Perfect!  Must have missed that in the documentation?  So is the default contains and with quotes an exact match?

**Comment by adback03** [comment]
Yup! Check [here](https://docs.pokemontcg.io/#api_v1cards_list) for the `name` parameter and its description. Glad it's working for you though!
