### ISSUE TITLE
Quick Shoutout 

### ISSUE THREAD

**Issue by crazcalm** [PokemonTCG/pokemon-tcg-api#83]
Thanks for making this API! I am looking forward to using it.
Also, I made an unofficial Go sdk https://github.com/crazcalm/go-pokemontcgsdk

Keep up the good work!

**Comment by adback03** [comment]
Awesome, thanks! Would you like a repo in the organization?

**Comment by crazcalm** [comment]
@adback03 YES! That would be awesome!!!

**Comment by adback03** [comment]
Sorry for the delay! Here you go: https://github.com/PokemonTCG/pokemon-tcg-sdk-go

You have been added as a contributor.

**Comment by crazcalm** [comment]
@adback03 Thanks! I have accepted the invitation. I should have the code up in the next few days.
