### ISSUE TITLE
404s on High Res images?

### ISSUE THREAD

**Issue by cssagogo** [PokemonTCG/pokemon-tcg-api#84]
I'm seeing a good deal of broken images, specifically for Majestic Dawn, but I haven't looked closely at others.  Currently it looks like you return a 404 and a default image (card back) in this case.  Can the broken images be fixed?  I'm also trying to think of the best way to detect these so that I can fall back on the low res version.  Would it be possible/make sense to return the low res version if you do not have the high res version? 

https://images.pokemontcg.io/dp5/73_hires.png
https://images.pokemontcg.io/dp5/51_hires.png
https://images.pokemontcg.io/dp5/49_hires.png
https://images.pokemontcg.io/dp5/99_hires.png
https://images.pokemontcg.io/dp5/59_hires.png
https://images.pokemontcg.io/dp5/47_hires.png
https://images.pokemontcg.io/dp5/66_hires.png
https://images.pokemontcg.io/dp5/76_hires.png
https://images.pokemontcg.io/dp5/80_hires.png
https://images.pokemontcg.io/dp5/100_hires.png
https://images.pokemontcg.io/dp5/89_hires.png 
https://images.pokemontcg.io/dp5/46_hires.png 
https://images.pokemontcg.io/dp5/58_hires.png 
https://images.pokemontcg.io/dp5/93_hires.png 
https://images.pokemontcg.io/dp5/63_hires.png 
https://images.pokemontcg.io/dp5/84_hires.png 
https://images.pokemontcg.io/dp5/90_hires.png 
https://images.pokemontcg.io/dp5/92_hires.png 
https://images.pokemontcg.io/dp5/53_hires.png 
https://images.pokemontcg.io/dp5/44_hires.png 
https://images.pokemontcg.io/dp5/52_hires.png 
https://images.pokemontcg.io/dp5/67_hires.png 
https://images.pokemontcg.io/dp5/75_hires.png 
https://images.pokemontcg.io/dp5/86_hires.png 
https://images.pokemontcg.io/dp5/50_hires.png 
https://images.pokemontcg.io/dp5/72_hires.png 
https://images.pokemontcg.io/dp5/54_hires.png 
https://images.pokemontcg.io/dp5/56_hires.png 
https://images.pokemontcg.io/dp5/83_hires.png 
https://images.pokemontcg.io/dp5/91_hires.png 
https://images.pokemontcg.io/dp5/60_hires.png 
https://images.pokemontcg.io/dp5/45_hires.png 
https://images.pokemontcg.io/dp5/71_hires.png 
https://images.pokemontcg.io/dp5/77_hires.png 
https://images.pokemontcg.io/dp5/81_hires.png 
https://images.pokemontcg.io/dp5/82_hires.png 
https://images.pokemontcg.io/dp5/88_hires.png 
https://images.pokemontcg.io/dp5/97_hires.png 
https://images.pokemontcg.io/dp5/98_hires.png 
https://images.pokemontcg.io/dp5/85_hires.png 
https://images.pokemontcg.io/dp5/43_hires.png 
https://images.pokemontcg.io/dp5/78_hires.png 
https://images.pokemontcg.io/dp5/55_hires.png 
https://images.pokemontcg.io/dp5/61_hires.png 
https://images.pokemontcg.io/dp5/64_hires.png 
https://images.pokemontcg.io/dp5/79_hires.png 
https://images.pokemontcg.io/dp5/65_hires.png 
https://images.pokemontcg.io/dp5/57_hires.png 
https://images.pokemontcg.io/dp5/74_hires.png

**Comment by adback03** [comment]
It does appear like I am missing those images for whatever reason. I'll try to gather those together (or if someone else beats me to it)

**Comment by adback03** [comment]
These images have been added. Thanks!
