### ISSUE TITLE
XY Black Star Promos showing as standard set

### ISSUE THREAD

**Issue by cssagogo** [PokemonTCG/pokemon-tcg-api#85]
The XY Black Star Promos set is showing standard for tournament type and should be marked as expanded.

**Comment by cssagogo** [comment]
code: "xyp"
expandedLegal: true
logoUrl: "https://images.pokemontcg.io/xyp/logo.png"
name: "XY Black Star Promos"
ptcgoCode: "PR-XY"
releaseDate: "10/12/2013"
series: "XY"
standardLegal: true **<-----**
symbolUrl: "https://images.pokemontcg.io/xyp/symbol.png"
totalCards: 183
updatedAt: "03/04/2018 10:35:00"

**Comment by r0adkll** [comment]
@adback03 Bump on this issue.

**Comment by adback03** [comment]
This has been resolved. Sorry for the delay!
