### ISSUE TITLE
Solgaleo GX - SM104 - Promo no found

### ISSUE THREAD

**Issue by Evhanz** [PokemonTCG/pokemon-tcg-api#86]
when I look for the letter of solgaleo-gx in the api, in the list that returns is not Solgaleo GX - SM104

**Comment by rastoAtGit** [comment]
I cant even find this card when searching for it at pokemon.com -https://www.pokemon.com/us/pokemon-tcg/pokemon-cards/?cardName=Solgaleo&cardText=&evolvesFrom=&simpleSubmit=&format=unlimited&hitPointsMin=0&hitPointsMax=250&retreatCostMin=0&retreatCostMax=5&totalAttackCostMin=0&totalAttackCostMax=5&particularArtist=. 
Is that normal?
Anyway, it's not just smp-SM104 but also smp-SM103 that is missing. I guess if you have all the data you can modify [pokemon-tcg-data](https://github.com/PokemonTCG/pokemon-tcg-data) to add these cards.

**Comment by jaymarvels** [comment]
Sometimes, especially for promo cards, they do not always appear on the pokemon website itself where the data is gathered from.

**Comment by adback03** [comment]
Closing, as this promo exists now...not sure when I got it added, but it has probably been in the data set for awhile now.
