### ISSUE TITLE
Individual banned card information

### ISSUE THREAD

**Issue by Sylencia** [PokemonTCG/pokemon-tcg-api#88]
While we have the "standardLegal" and "expandedLegal" available for overall sets, some cards such as Lusamine are currently legal in standard but not in expanded due to the ban list. Cards should have an individual field that contains the legality status of the card.

The full list can be found at https://www.pokemon.com/us/pokemon-tcg-banned-card-list/

**Comment by adback03** [comment]
Legality info at a card level will be in the new API. A beta of this API will be out in the next couple weeks.

**Comment by adback03** [comment]
This is no longer an issue with V2. Cards have their own legality block now.
