### ISSUE TITLE
Pokemon::Set.find('xy1') no longer returns all options just a subset [RUBY]

### ISSUE THREAD

**Issue by aymenbuu** [PokemonTCG/pokemon-tcg-api#89]
I can no longer retrieve logo_url or image_url for a set using the Ruby SDK.

It only gives me a subset of the overal fields for a set.

**Comment by aymenbuu** [comment]
curl "https://api.pokemontcg.io/v1/sets/xy1"
{"set":{"code":"xy1","ptcgoCode":"XY","name":"XY","series":"XY","totalCards":146,"standardLegal":false,"expandedLegal":true,"releaseDate":"02/05/2014","symbolUrl":"https://images.pokemontcg.io/xy1/symbol.png","logoUrl":"https://images.pokemontcg.io/xy1/logo.png","updatedAt":"03/04/2018 10:35:00"}}

However when using the Ruby SDK , the logoUrl and symbolUrl are not made available.

**Comment by adback03** [comment]
image_url is only a valid field on a card, not a set. You are looking for symbol_url and logo_url. I just tested this with the Ruby SDK and could not reproduce.

```
require 'pokemon_tcg_sdk'

set = Pokemon::Set.find('xy1')

puts set.logo_url
puts set.symbol_url
```
The following was output in my terminal:

https://images.pokemontcg.io/xy1/logo.png
https://images.pokemontcg.io/xy1/symbol.png

Please make sure you are using version 3.0.0 of the SDK and try again. Maybe post the script you are using here as well.
