### ISSUE TITLE
Query by pokedex ID

### ISSUE THREAD

**Issue by ridhwaans** [PokemonTCG/pokemon-tcg-api#93]
Is there an option in the API to query card by national pokedex ID. it seems like such as common use case. I understand currently the way to search generation I cards are by retrieving base, fossil & jungle sets. There should be another way to fetch the trading cards of all 151 original pokemon

**Comment by adback03** [comment]
Yes, this functionality exists:

```
https://api.pokemontcg.io/v1/cards?nationalPokedexNumber=1
```
