### ISSUE TITLE
Support for querying a card by its ptcgoCode

### ISSUE THREAD

**Issue by daltonclaybrook** [PokemonTCG/pokemon-tcg-api#94]
Often when you see a card referenced online, it will be accompanied with a format `<ptcgoCode>-<number>` (e.g. TEU-53). Since this code is not a supported query parameter on the cards endpoint, we must make two separate requests to find this card:

One to get the `setCode`:
`/sets?ptcgoCode=TEU`
And another to get the card:
`/cards?number=53&setCode=<code>`

If `ptcgoCode` were available as a query parameter on the cards endpoint, we would only need to make one request:
`/cards?number=53&ptcgoCode=TEU`

**Comment by adback03** [comment]
This is no longer an issue with V2, as set data is embedded on the card as well.

`/v2/cards?q=set.ptcgoCode=TEU number:53`
