### ISSUE TITLE
Card HP is documented as int but transferred as string

### ISSUE THREAD

**Issue by Serraniel** [PokemonTCG/pokemon-tcg-api#96]
In the documentation HP is documented as integer: https://docs.pokemontcg.io/api-reference/cards/card-object#hp-integer 

However, in the JSON object it´s transferred as a string. Probably a minor issue but if implementing according to the docs it´s causing exceptions in some languages probably, like it happened for me:
> System.Text.Json.JsonException : The JSON value could not be converted to System.Nullable`1[System.Int32]. Path: $.data[0].hp | LineNumber: 0 | BytePositionInLine: 106.
  ----> System.InvalidOperationException : Cannot get the value of a token type 'String' as a number.

Handling it is not an issue, but I wanted to suggest you to change it to string in the documentation as I assume migrating the API to transfer an actual integer may break other implementations who adopted to it already.

**Comment by adback03** [comment]
Closing as this has been resolved.
