### ISSUE TITLE
Add cardmarket pricing data

### ISSUE THREAD

**Issue by Akkora** [PokemonTCG/pokemon-tcg-api#97]
Hello @adback03,

first of all: thank you for providing this nice project! I just started using the api and I really enjoy it.

Regarding the pricing, is there a way to add prices of [cardmarket](https://www.cardmarket.com)? It is the major european place for selling cards online. The prices for some cards are quite different than the ones on TCGplayer. They come with their own api. Documentation can be found [here](https://api.cardmarket.com/ws/documentation).

If I can support you with anymore details don't hesitate to contact me.

**Comment by jaymarvels** [comment]
My personal preference is that this API shouldn't include cardmarket prices and developers should query it themselves directly.

Doesn't make sense in terms of separation of responsibility or what this api is defined as

**Comment by adback03** [comment]
Cardmarket and TCGplayer pricing is already available in the API.

https://docs.pokemontcg.io/api-reference/cards/card-object#cardmarket-hash

If you are still using version 1 of the API, then you wouldn't have this data as it is only available in V2.
